# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/HPParallaxHeader.xcworkspace -scheme HPParallaxHeader-Example -destination 'platform=iOS Simulator,OS=11.1,name=iPhone 6 Plus' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
